// live-tab-instrument: paste/eval this into any tab to capture
// dataLayer pushes + outbound tracking beacons + WPForms submits.
// Output accumulates on window.__livProbe; read it with __livProbe.dump().
//
// Self-contained. No deps. Idempotent (safe to run twice).
//
// Generated by tools/diagnostics/live-tab-instrument/index.js — do not edit the
// runtime payload here without also keeping the index.js source in sync.
(function () {
  'use strict';

  if (window.__livProbe && window.__livProbe.__installed) {
    console.log('[livProbe] already installed; state preserved');
    return window.__livProbe;
  }

  const state = {
    __installed: true,
    installedAt: new Date().toISOString(),
    pushes: [],        // dataLayer.push observations
    beacons: [],       // outbound network calls of interest
    submits: [],       // WPForms submits seen
    errors: [],
    config: { trackedHosts: /googleadservices\.com|google-analytics\.com|googletagmanager\.com|analytics\.google\.com/i },
  };

  // --- 1. dataLayer.push hook ---
  try {
    const existing = Array.isArray(window.dataLayer) ? window.dataLayer : [];
    const origPush = existing.push ? existing.push.bind(existing) : Array.prototype.push.bind(existing);
    existing.push = function (...args) {
      try {
        const safe = args.map((a) => {
          if (!a || typeof a !== 'object') return a;
          const clone = Array.isArray(a) ? [] : {};
          for (const [k, v] of Object.entries(a)) {
            if (typeof v === 'string' && v.length > 200) clone[k] = '[len=' + v.length + ']';
            else if (typeof v === 'function') clone[k] = '[fn]';
            else if (v && typeof v === 'object') {
              try { clone[k] = JSON.parse(JSON.stringify(v)); }
              catch (_) { clone[k] = '[unserializable]'; }
            } else clone[k] = v;
          }
          return clone;
        });
        state.pushes.push({ ts: Date.now(), args: safe });
      } catch (e) {
        state.errors.push({ where: 'push-hook', msg: String(e.message).slice(0, 200) });
      }
      return origPush(...args);
    };
    window.dataLayer = existing;
  } catch (e) {
    state.errors.push({ where: 'install-push', msg: String(e.message).slice(0, 200) });
  }

  // --- 2. fetch hook ---
  try {
    const origFetch = window.fetch;
    window.fetch = async function (input, init) {
      try {
        const url = typeof input === 'string' ? input : (input && input.url) || '';
        const method = (init && init.method) || (typeof input === 'object' && input && input.method) || 'GET';
        observeBeacon({ url, method, body: init && init.body, kind: 'fetch' });
        observeSubmit({ url, method, body: init && init.body });
      } catch (e) { state.errors.push({ where: 'fetch-hook', msg: e.message.slice(0, 200) }); }
      return origFetch.apply(this, arguments);
    };
  } catch (e) {
    state.errors.push({ where: 'install-fetch', msg: String(e.message).slice(0, 200) });
  }

  // --- 3. XHR hook ---
  try {
    const origOpen = XMLHttpRequest.prototype.open;
    const origSend = XMLHttpRequest.prototype.send;
    XMLHttpRequest.prototype.open = function (method, url) {
      this.__livProbeUrl = url;
      this.__livProbeMethod = method;
      return origOpen.apply(this, arguments);
    };
    XMLHttpRequest.prototype.send = function (body) {
      try {
        observeBeacon({ url: this.__livProbeUrl, method: this.__livProbeMethod, body, kind: 'xhr' });
        observeSubmit({ url: this.__livProbeUrl, method: this.__livProbeMethod, body });
      } catch (e) { state.errors.push({ where: 'xhr-hook', msg: e.message.slice(0, 200) }); }
      return origSend.apply(this, arguments);
    };
  } catch (e) {
    state.errors.push({ where: 'install-xhr', msg: String(e.message).slice(0, 200) });
  }

  // --- 4. sendBeacon hook ---
  try {
    if (navigator.sendBeacon) {
      const origBeacon = navigator.sendBeacon.bind(navigator);
      navigator.sendBeacon = function (url, body) {
        try { observeBeacon({ url, method: 'POST', body, kind: 'sendBeacon' }); }
        catch (e) { state.errors.push({ where: 'beacon-hook', msg: e.message.slice(0, 200) }); }
        return origBeacon(url, body);
      };
    }
  } catch (e) {
    state.errors.push({ where: 'install-beacon', msg: String(e.message).slice(0, 200) });
  }

  function observeBeacon({ url, method, body, kind }) {
    const u = String(url || '');
    if (!state.config.trackedHosts.test(u)) return;
    const entry = {
      ts: Date.now(),
      kind,
      method: String(method || 'GET').toUpperCase(),
      host: hostOf(u),
      classify: classify(u),
      url: u.length > 350 ? u.slice(0, 350) + '…' : u,
      params: paramsOf(u),
      body: decodeBody(body),
    };
    state.beacons.push(entry);
  }

  function observeSubmit({ url, body }) {
    const u = String(url || '');
    const b = body ? String(body) : '';
    if (!/admin-ajax|wpforms/i.test(u)) return;
    const formIdMatch = b.match(/wpforms%5Bid%5D=(\d+)|wpforms\[id\]=(\d+)/);
    state.submits.push({
      ts: Date.now(),
      url: u.length > 200 ? u.slice(0, 200) + '…' : u,
      formId: formIdMatch ? (formIdMatch[1] || formIdMatch[2]) : null,
      bodyLen: b.length,
    });
  }

  function hostOf(url) { try { return new URL(url).host; } catch (_) { return ''; } }
  function classify(url) {
    if (url.includes('googleadservices.com/pagead/conversion')) return 'google-ads-conversion';
    if (url.includes('google-analytics.com/g/collect')) return 'ga4-collect';
    if (url.includes('analytics.google.com/g/collect')) return 'ga4-collect';
    if (url.includes('google-analytics.com/collect')) return 'ga-classic-collect';
    if (url.includes('googletagmanager.com/gtm.js')) return 'gtm-loader';
    if (url.includes('googletagmanager.com/gtag/js')) return 'gtag-loader';
    if (url.includes('googletagmanager.com/a')) return 'gtm-heartbeat';
    return 'other';
  }
  function paramsOf(url) {
    try {
      const u = new URL(url);
      const out = {};
      for (const [k, v] of u.searchParams.entries()) {
        out[k] = v.length > 120 ? '[len=' + v.length + ']' : v;
      }
      return out;
    } catch (_) { return null; }
  }
  function decodeBody(body) {
    if (!body) return null;
    if (typeof body !== 'string') {
      try { body = String(body); } catch (_) { return '[binary]'; }
    }
    if (body.length > 4000) return '[len=' + body.length + ']';
    if (body.includes('=') && body.includes('&')) {
      try {
        const out = {};
        for (const pair of body.split('&')) {
          const [k, v] = pair.split('=');
          const kk = decodeURIComponent(k || '');
          const vv = decodeURIComponent((v || '').replace(/\+/g, ' '));
          // mask anything that looks like an email or phone or long token
          if (/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(vv)) out[kk] = '[email]';
          else if (/^\+?\d[\d\-\s()]{6,}$/.test(vv)) out[kk] = '[phone]';
          else out[kk] = vv.length > 120 ? '[len=' + vv.length + ']' : vv;
        }
        return out;
      } catch (_) { return body.slice(0, 500); }
    }
    return body.slice(0, 500);
  }

  state.dump = function () {
    return {
      installedAt: state.installedAt,
      now: new Date().toISOString(),
      counts: { pushes: state.pushes.length, beacons: state.beacons.length, submits: state.submits.length, errors: state.errors.length },
      pushes: state.pushes,
      beacons: state.beacons,
      submits: state.submits,
      errors: state.errors,
    };
  };
  state.summary = function () {
    const eventNames = state.pushes
      .map(p => (p.args && p.args[0] && p.args[0].event) || null)
      .filter(Boolean);
    const beaconKinds = {};
    for (const b of state.beacons) beaconKinds[b.classify] = (beaconKinds[b.classify] || 0) + 1;
    return { eventNames, beaconKinds, submitCount: state.submits.length };
  };
  state.reset = function () { state.pushes = []; state.beacons = []; state.submits = []; state.errors = []; };

  window.__livProbe = state;
  console.log('[livProbe] installed. Trigger your action, then read window.__livProbe.dump()');
  return state;
})();
