'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');
const io=require('../research-io.cjs');const {hashObject}=require('../../../ticktock/canonical.cjs');
const digest=v=>crypto.createHash('sha256').update(v).digest('hex');
function fixture(){const repoRoot=fs.mkdtempSync(path.join(os.tmpdir(),'research-contract-'));for(const p of Object.keys(io.sourceIdentities())){fs.mkdirSync(path.dirname(path.join(repoRoot,p)),{recursive:true});fs.copyFileSync(path.join(io.ROOT,p),path.join(repoRoot,p));}return repoRoot;}
function capability(repoRoot){const source_identities_sha256=hashObject(io.sourceIdentities(repoRoot));const evidence={schema:'ResearchVerification/1.0',status:'pass',source_identities_sha256,checks:{adapter_equivalence:true,accounting:true,isolation:true,reproducibility:true},fixture:true};const review={schema:'ResearchImplementationReview/1.0',status:'pass',source_identities_sha256,producer_family:'fixture-producer',reviewer_family:'fixture-reviewer',fixture:true};const base='_dev/sim-runs/research/_capabilities/';fs.mkdirSync(path.join(repoRoot,base),{recursive:true});function save(name,value){const bytes=JSON.stringify(value);fs.writeFileSync(path.join(repoRoot,base+name),bytes);return {path:base+name,sha256:digest(bytes)};}const receipt={schema:'ResearchCapability/1.0',source_identities_sha256,evidence:save('test-evidence.json',evidence),review:save('test-review.json',review)};save('rg01.json',receipt);}
function prepared(root,batch='test',goal='RG-01'){return io.prepare({repoRoot:root,batchId:batch,goalId:goal,charterHash:'a'.repeat(64),rounds:2,seeds:[1]});}
test('strict experiments, capability evidence and immutable selection',()=>{const root=fixture();try{const p=prepared(root);const o={repoRoot:root,charterHash:'a'.repeat(64),cycleIndex:0,specPath:p.spec_path};assert.equal(io.readiness(o).status,'not_ready');capability(root);assert.equal(io.readiness(o).status,'ready');assert.equal(io.selectionReadiness({...o,bind:true}).selection_bound,true);assert.throws(()=>io.selectionReadiness({...o,specPath:undefined}),/omitted/);assert.throws(()=>prepared(root),/already exists/);const bytes=fs.readFileSync(path.join(root,p.spec_path));fs.appendFileSync(path.join(root,p.spec_path),'\n');assert.throws(()=>io.selectionReadiness(o),/changed/);fs.writeFileSync(path.join(root,p.spec_path),bytes);const altered={...p.experiment,primary_goal:'RG-99'};assert.equal(io.validateExperiment(altered),false);altered.primary_goal='RG-01';altered.primary_goals=['RG-01','RG-02'];assert.equal(io.validateExperiment(altered),false);fs.appendFileSync(path.join(root,'tools/ticktock/cycle-driver.cjs'),'\n');assert.throws(()=>io.readiness(o),/stale source/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('unknown, unsupported, traversal and symlink refuse safely',()=>{const root=fixture();try{assert.throws(()=>prepared(root,'bad','RG-99'),/unknown/);const p=prepared(root,'later','RG-02');capability(root);assert.equal(io.readiness({repoRoot:root,specPath:p.spec_path,charterHash:'a'.repeat(64)}).status,'not_ready');assert.throws(()=>io.safePath(root,'../escape'),/unsafe/);fs.symlinkSync(os.tmpdir(),path.join(root,'escape'));assert.throws(()=>io.safePath(root,'escape/out'),/symlink/);assert.throws(()=>prepared(root,'../escape'),/invalid batch/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
module.exports={fixture,capability,prepared};
test('prepare CLI bounds wall budget and round/decision units before mutation',()=>{const {parseArgs}=require('../../../ticktock/research-prepare.cjs');assert.equal(parseArgs(['draft.json','new']).maxWallMs,300000);assert.equal(parseArgs(['draft.json','new','--max-wall-ms=120000']).maxWallMs,120000);for(const value of ['NaN','Infinity','0','-1','3600001','1.5'])assert.throws(()=>parseArgs(['draft.json','new','--max-wall-ms='+value]),/max-wall-ms/);assert.throws(()=>parseArgs(['draft.json','new','--max-wall-ms=100','--max-wall-ms=200']),/duplicate/);const root=fixture();try{const p=io.prepare({repoRoot:root,batchId:'units',charterHash:'a'.repeat(64),rounds:3,seeds:[1],maxWallMs:300000});assert.equal(p.experiment.limits.max_ticks,3);assert.equal(p.experiment.limits.max_decisions,6);assert.equal(p.experiment.limits.max_wall_ms,300000);assert.doesNotThrow(()=>io.loadExperiment({repoRoot:root,specPath:p.spec_path,charterHash:'a'.repeat(64)}));for(const value of [NaN,Infinity,0,-1,3600001,1.5])assert.throws(()=>io.prepare({repoRoot:root,batchId:'rejected',charterHash:'a'.repeat(64),maxWallMs:value}),/invalid experiment/);assert.equal(fs.existsSync(path.join(root,'_dev/sim-runs/research/_drafts/rejected.json')),false);}finally{fs.rmSync(root,{recursive:true,force:true});}});
