'use strict';

const fs = require('fs');
const path = require('path');

function splitArgs(argsText) {
  return String(argsText || '').match(/"[^"]*"|'[^']*'|\S+/g)?.map((token) => {
    if ((token.startsWith('"') && token.endsWith('"')) || (token.startsWith("'") && token.endsWith("'"))) {
      return token.slice(1, -1);
    }
    return token;
  }) || [];
}

function parseArgs(argsText) {
  const tokens = splitArgs(argsText);
  const opts = {
    scope: '',
    force: false
  };
  for (const token of tokens) {
    if (token === '--force') opts.force = true;
    else if (!token.startsWith('--') && !opts.scope) opts.scope = token;
  }
  return opts;
}

function rel(projectRoot, filePath) {
  return path.relative(projectRoot, filePath).replace(/\\/g, '/');
}

function sanitizeScope(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'general';
}

function walkFiles(dirPath, limit = 5000) {
  const out = [];
  function walk(current) {
    if (out.length >= limit || !fs.existsSync(current)) return;
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      if (out.length >= limit) return;
      const filePath = path.join(current, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === 'session-bundles' || entry.name === 'archive') continue;
        walk(filePath);
      } else if (entry.isFile()) {
        out.push(filePath);
      }
    }
  }
  walk(dirPath);
  return out;
}

function gatherEvidence(projectRoot, scope) {
  const analysisDir = path.join(projectRoot, '_dev', 'reports', 'analysis');
  const safeScope = sanitizeScope(scope);
  const direct = [
    path.join(analysisDir, 'task-plans', `${safeScope}__plan.json`),
    path.join(analysisDir, 'task-plans', `${safeScope}__plan.md`),
    path.join(analysisDir, 'task-plan-reviews', `${safeScope}__review.json`),
    path.join(analysisDir, 'task-plan-reviews', `${safeScope}__review.md`)
  ].filter((filePath) => fs.existsSync(filePath));

  const topLevel = walkFiles(analysisDir)
    .filter((filePath) => {
      const base = path.basename(filePath).toLowerCase();
      if (!/\.(md|json)$/.test(base)) return false;
      if (base.startsWith(`run-debrief__${safeScope}`)) return false;
      return base.includes(safeScope);
    });

  return Array.from(new Set([...direct, ...topLevel]))
    .sort()
    .slice(0, 20)
    .map((filePath) => rel(projectRoot, filePath));
}

function renderDebriefMarkdown(scope, debriefedAt, evidenceRefs) {
  const lines = [];
  lines.push(`# Run Debrief: ${scope}`);
  lines.push('');
  lines.push(`**Scope:** \`${scope}\``);
  lines.push(`**Debriefed at:** ${debriefedAt}`);
  lines.push('**Status:** deterministic debrief artifact generated');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('The deterministic `/debrief-run` handler resolved the requested scope and wrote the canonical debrief artifact set. It did not infer corrective lessons beyond the available evidence.');
  lines.push('');
  lines.push('Framework delta: no framework delta was identified automatically. The deterministic handler is intentionally conservative; framework improvements should be added only when evidence supports a specific improve item.');
  lines.push('');
  lines.push('## Findings');
  lines.push('');
  lines.push('No actionable improve or replicate findings were generated by the deterministic handler.');
  lines.push('');
  lines.push('## Evidence');
  lines.push('');
  if (evidenceRefs.length === 0) {
    lines.push('- No matching evidence artifacts were found for this scope.');
  } else {
    for (const ref of evidenceRefs) lines.push(`- ${ref}`);
  }
  lines.push('');
  lines.push('## Push Readiness');
  lines.push('');
  lines.push('Not assessed by the deterministic handler. Use implementation review and scoped clean-house evidence before commit or push.');
  lines.push('');
  return lines.join('\n');
}

function debriefRun(projectRoot, argsText, options = {}) {
  const args = parseArgs(argsText);
  if (!args.scope || args.scope === 'latest') {
    return {
      exitCode: 2,
      stdout: '',
      stderr: 'Deterministic /debrief-run requires an explicit scope in this first slice.'
    };
  }

  const analysisDir = path.join(projectRoot, '_dev', 'reports', 'analysis');
  const safeScope = sanitizeScope(args.scope);
  const debriefPath = path.join(analysisDir, `run-debrief__${safeScope}.md`);
  const improvePath = path.join(analysisDir, `run-debrief__${safeScope}.improve-plan.json`);
  const replicatePath = path.join(analysisDir, `run-debrief__${safeScope}.replicate-plan.json`);

  const existing = [debriefPath, improvePath, replicatePath].filter((filePath) => fs.existsSync(filePath));
  if (existing.length > 0 && !args.force && options.write !== false) {
    return {
      exitCode: 2,
      stdout: '',
      stderr: `Debrief artifacts already exist for ${args.scope}; re-run with --force to overwrite: ${existing.map((filePath) => rel(projectRoot, filePath)).join(', ')}`
    };
  }

  const debriefedAt = new Date().toISOString();
  const evidenceRefs = gatherEvidence(projectRoot, args.scope);
  const improve = {
    scope: args.scope,
    debriefed_at: debriefedAt,
    items: []
  };
  const replicate = {
    scope: args.scope,
    debriefed_at: debriefedAt,
    items: []
  };

  const payload = {
    ok: true,
    scope: args.scope,
    artifacts: {
      markdown: rel(projectRoot, debriefPath),
      improve_plan: rel(projectRoot, improvePath),
      replicate_plan: rel(projectRoot, replicatePath)
    },
    evidence_refs: evidenceRefs,
    findings_generated: 0,
    dry_run: options.write === false,
    would_overwrite: existing.map((filePath) => rel(projectRoot, filePath))
  };
  if (options.write === false) {
    return {
      exitCode: 0,
      stdout: options.json === false
        ? `Would write debrief artifacts for ${args.scope}`
        : JSON.stringify(payload, null, 2),
      stderr: ''
    };
  }

  fs.mkdirSync(analysisDir, { recursive: true });
  fs.writeFileSync(debriefPath, renderDebriefMarkdown(args.scope, debriefedAt, evidenceRefs));
  fs.writeFileSync(improvePath, JSON.stringify(improve, null, 2) + '\n');
  fs.writeFileSync(replicatePath, JSON.stringify(replicate, null, 2) + '\n');
  return {
    exitCode: 0,
    stdout: options.json === false
      ? `Wrote debrief artifacts for ${args.scope}`
      : JSON.stringify(payload, null, 2),
    stderr: ''
  };
}

module.exports = {
  debriefRun,
  gatherEvidence,
  parseArgs,
  sanitizeScope
};
